train_url=${0%%.sh}
train_url=${train_url:21}
python main_moco.py \
--moxing=false \
--train_url=/cache/${train_url} \
--data_dir=/cache/data/imagenet2012/ \
--moco_dim=128 \
--moco_k=65536 \
--moco_m=0.999 \
--moco_t=0.2 \
--mlp=true \
--aug_plus=true \
--decay_method=cos \
--init_lr=0.03 \
--batch_size=512 \
--num_workers=64 \
--end_epoch=200 \
--dist=true \
--nodes_num=4 \
--node_rank=0 \
--subgroup=4 \
--master_addr=10.0.9.145 \
# --resume=true \
